#!/usr/bin/env bash
#one bash script managing another

if [ "$1" == "Start" ]
then
    manage_my_process &
    echo $! > /var/run/my_process.pid
    echo "manage_my_process started"
elif
    [ "$1" == "Stop" ]
then
    kill manage_my_process
    rm -f /var/run/my_process.pid
    echo "manage_my_process stopped"
elif
    [ "$1" == restart ]
then
    kill manage_my_process
    rm -f /var/run/my_process.pid
    manage_my_process &
    echo $! > /var/run/my_process.pid
    echo "manage_my_process started"
else
    echo "Usage: manage_my_process {start|stop|restart} "
fi
