#!/usr/bin/env bash
#one bash script managing another
PIDFILE="/var/run/my_process.pid"
process="bash manage_my_process"

start_process (){
    $process &
    echo $! > $PIDFILE
    echo "manage_my_process started"
}

stop_process (){
    pkill $process
    rm -f $PIDFILE
    echo "manage_my_process stopped"
}
restart_process (){
    pkill $process
    rm -f $PIDFILE
    $process &
    echo $! > $PIDFILE
    echo "manage_my_process restarted"
}

case "$1" in
    start)
        start_process
        ;;
    stop)
        stop_process
        ;;
    restart)
        restart_process
        ;;
    *)
    echo "Usage: manage_my_process {start|stop|restart}"
esac
