#!/usr/bin/env bash
#Displays the phrase "To Infity an Beyond" in the terminal in a loop, with  a delay of 2 seconds per iteration, and can be stopped by the user using Ctrl+C
while true; do
    echo "To infinity and beyond"
    sleep 2
done

